#logging:
#  level:
#    ROOT: DEBUG

spring:
#  profiles:
#    active: dev
#    include:
#      - swagger

#  devtools:
#    restart:
#      enabled: true
#      additional-exclude: static/**
#    livereload:
#      enabled: true
#  jackson:
#    serialization:
#      indent-output: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/lwm2m-db
#      uri: mongodb://AscUser:AltShift$93058@localhost:27017/lwm2m-db
#      port: 27017
#      database: lwm2m-db
#      username: MongoUser
#      password:
#      - A

security:
  jwt:
    secret: XNPEklRL6ipppDu4zmpZ5wAIcZH0TiKsiqdoylFpP48ap1lCJdiyh1SiFZe3Xbizhu91WiV3Jmbw+XGH5Mip8s6Yrl7N6jLCza0aZNstMDgNYa6eGpkjmpqvQUnqo62flpiUzCldVh5oTCFL9puA1yx0a2ZiRJRZ93PYS7hFIsc9P7OIp3oqJ3B/VB7GE+DKzCWDEWLPt/3b77klJ/MNw16gtIgASZUZXtPLyQ==

server:
  address: localhost
  port: 9090

coap:
  secure-address: localhost
  secure-port: 5686

tb:
  base-url: http://localhost:8080/api
  username: tenant@thingsboard.org
  password: tenant
  provision:
    key: r3rd5n77w1bpht21kp91
    secret: i9x798wdnbzirnax7b43
