#logging:
#  level:
#    ROOT: DEBUG

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    enabled: false # By default, the JHipster Registry is not used in the "dev" profile
#    service-url:
#      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/

spring:
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: true
  jackson:
    serialization:
      indent-output: true
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: lwm2m-db
#  mail:
#    host: localhost
#    port: 25
#    username:
#    password:
#  messages:
#    cache-duration: PT1S # 1 second, see the ISO 8601 standard
#  thymeleaf:
#    cache: false
#  sleuth:
#    sampler:
#      probability: 1 # report 100% of traces
#  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
#    base-url: http://localhost:9411
#    enabled: false
#    locator:
#      discovery:
#        enabled: true

server:
  port: 9090
